#!/bin/bash
#
#SBATCH --job-name=building_poscars
#SBATCH --output=output/poscars_out
#
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH -p chem.default.q

# Go to directory with local python environment
cd 

# Activate python environment
source env/bin/activate

# Go to directory where the scripts are
cd VASP/automated_runs/

# Run python to build poscars
python3 build_poscars.py 


