#!/bin/bash
#
#SBATCH --job-name=vis_plots
#SBATCH --output=output/visout
#
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH -p chem.default.q

# Go to base directory
cd 

# Activate local python environment
source env/bin/activate

# Go to directory with files
cd VASP/automated_runs/


python3 visualise.py 
